Description of generate_banks
Home > FinalCode > generate_banks.m
generate_banks
PURPOSE
Function to generate values of the banking system. This is the vanilla bank
SYNOPSIS
function [B, a, e, i, c, d, b, w] = generate_banks(N, p, gamma, theta, E,type)
DESCRIPTION
Function to generate values of the banking system. This is the vanilla bank
generation function written by the group of the previous year, and no changes have been made
apart from the inclusion of a new parameter 'type' that tells the function to generate a
random network or a scale free network.
CROSS-REFERENCE INFORMATION
This function calls:
pref_graph This function is created entirely by our group.
random_graph This function is created by the previous group, and not adjusted for our
This function is called by:
test_setups_standard This script is used to compare the random network to the scale free network in
SOURCE CODE
function [B, a, e, i, c, d, b, w] = generate_banks(N, p, gamma, theta, E,type)
%Function to generate values of the banking system. This is the vanilla bank
%generation function written by the group of the previous year, and no changes have been made
%apart from the inclusion of a new parameter 'type' that tells the function to generate a
%random network or a scale free network.
if type == 0
    B = random_graph(N,p); % B = the unidirectional banking system Graph
    % as N*N Array of 0 and 1
elseif type == 1
    B = pref_graph(N,p,p);
end
beta = 1-theta; % = percentage of external assets in total assets
A = E / beta;   % = total Assets
I = theta * A;  % = aggregate size of interbank exposures
Z = sum(sum(B));% = number of links
w = I / Z;      % = weight of any link, to define the interbank assets of a bank
if Z==0
    w=0;        % Set w and therefor also b and i to 0 if there is no link
end
i = sum(B,2)'* w; % = interbank assets per bank as number of outgoing links times the weight
b = sum(B,1) * w; % = interbank borrowing per bank as number of incoming links times the weight
% two steps to calculate e = external assets per bank
e = b - i;              % to fulfil e >= b - i
e = e + (E - sum(e))/N; % distribute the rest of E evenly among all banks
a = e + i;     % = total assets per bank
c = gamma * a; % = net worth per bank
d = a - c - b; % = consumer deposits per Bank
end